#!/bin/bash


cd /home/nexus/sites/waypoints && gitq && cd ~/rp4 && gitp && cd /home/nexus/sites/waypoints/nexus/scripts/ReadyPlayerFour

echo "BUILD COMPLETE - CHECK UNITY" | lolcat









# # Stop UnrealEditor process
# echo 'powershell.exe Stop-Process -Name "UnrealEditor"' | lolcat
# powershell.exe Stop-Process -Name "UnrealEditor"  > /home/nexus/sites/waypoints/nexus/scripts/ReadyPlayerFour/logs/gitqc.log
# # Compile with Git and Make
# echo "gitqc [Compile]" | lolcat
# cd ~/sites/waypoints && gitq
# if [ $? -ne 0 ]; then
#     echo "🔴🔴🔴 ERROR 🔴🔴🔴 - gitq failed"
#     exit 1
# fi

# cd ~/rp4 && gitp
# if [ $? -ne 0 ]; then
#     echo "🔴🔴🔴 ERROR 🔴🔴🔴 - gitp failed"
#     exit 1
# fi

# cd /home/nexus/sites/waypoints/nexus/scripts/ReadyPlayerFour/
# make rebuild > /home/nexus/sites/waypoints/nexus/q/q.log
# if [ $? -ne 0 ]; then
#     echo "🔴🔴🔴 ERROR 🔴🔴🔴 - make rebuild failed"
#     cat /home/nexus/sites/waypoints/nexus/q/q.log
#     exit 1
# fi


# # # Open Unreal Editor
# # explorer.exe "C:\Users\nkuhn\Documents\Unreal Projects\waypoints\nexus\scripts\ReadyPlayerFour\ReadyPlayerFour.uproject"
